---
# apt packages to install
kali_packages:
  - assetfinder
  - awscli
  - bettercap
  - bloodhound
  - build-essential
  - chromium
  - docker.io
  - docker-compose
  - dnsutils
  - eyewitness
  - ffuf
  - gdb
  - gdbserver
  - gem
  - gobuster
  - golang
  - jq
  - libpcap-dev
  - libssl-dev
  - libbz2-dev 
  - libreadline-dev
  - libsqlite3-dev 
  - libncurses5-dev 
  - libncursesw5-dev
  - liblzma-dev 
  - mimikatz
  - ncat
  - nbtscan-unixwiz
  - neo4j
  - npm
  - parallel
  - powershell-empire
  - python3-openssl
  - python3-pip
  - python3-venv
  - seclists
  - spiderfoot
  - sublist3r
    
# pip packages    
pip_packages:
  - Cython
  - dirhunt
  - getsploit
  - ldap3  
  - mitm6
  - minikerberos
  - pipenv
  - poetry
  - python3-ldap
  - python-libpcap
  - pywhat
  - requests
  - unicorn

# Gem Packages -- still needs added as task
gem_packages:
  - pass-station
  - wpscan

# Group ownership for the tools that are installed directly to /opt
group: kali
user: kali

# Base directory where all manually-installed tools will be installed
git_base_dir: "/opt"

# Tools to be manually installed
git_repos:
  - {dir_name: "bloodhound", repo: "https://github.com/fox-it/BloodHound.py.git"} 
  - {dir_name: "certi", repo: "https://github.com/zer1t0/certi.git"}
  - {dir_name: "certipy", repo: "https://github.com/ly4k/Certipy.git"}
  - {dir_name: "checkpwnedemails", repo: "https://github.com/Techno-Hwizrdry/checkpwnedemails.git"}
  - {dir_name: "CMSmap", repo: "https://github.com/dionach/CMSmap.git"}
  - {dir_name: "dirsearch", repo: "https://github.com/maurosoria/dirsearch.git"}
  - {dir_name: "google-dork-scan", repo: "https://github.com/IvanGlinkin/Fast-Google-Dorks-Scan.git"}
  - {dir_name: "github-search", repo: "https://github.com/gwen001/github-search.git"}
  - {dir_name: "gnmap-parser", repo: "https://github.com/ChrisTruncer/gnmap-parser.git"}
  - {dir_name: "Hasher", repo: "https://github.com/FortyNorthSecurity/Hasher.git"}
  - {dir_name: "ImpDump", repo: "https://github.com/HarmJ0y/ImpDump.git"}
  - {dir_name: "impacket", repo: "https://github.com/SecureAuthCorp/impacket.git"}
  - {dir_name: "JSscanner", repo: "https://github.com/dark-warlord14/JSScanner.git"}
  - {dir_name: "knockpy", repo: "https://github.com/guelfoweb/knock.git"}
  - {dir_name: "mikto", repo: "https://github.com/ChrisTruncer/mikto.git"}
  - {dir_name: "nlzr", repo: "https://github.com/noahpowers/nlzr.git"}
  - {dir_name: "o365spray", repo: "https://github.com/hackedbyagirl/o365spray.git"}
  - {dir_name: "PCredz", repo: "https://github.com/lgandx/PCredz.git"}
  - {dir_name: "Pentest-Scripts", repo: "https://github.com/averagesecurityguy/scripts.git"}
  - {dir_name: "PetitPotam", repo: "https://github.com/topotam/PetitPotam.git"}
  - {dir_name: "PKINITtools", repo: "https://github.com/dirkjanm/PKINITtools"}
  - {dir_name: "pywhisker", repo: "https://github.com/ShutdownRepo/pywhisker.git"}
  - {dir_name: "quieter-firefox", repo: "https://bitbucket.org/mrbbking/quieter-firefox.git"}
  - {dir_name: "SimplyEmail", repo: "https://github.com/SimplySecurity/SimplyEmail.git"}
  - {dir_name: "spiderfoot", repo: "https://github.com/smicallef/spiderfoot.git"} 
  - {dir_name: "Token-Reverser", repo: "https://github.com/dariusztytko/token-reverser.git"}

# aquatone, which is installed manually
aquatone: "https://github.com/michenriksen/aquatone/releases/download/v1.7.0/aquatone_linux_amd64_1.7.0.zip"
