---
- name: apt-update packages
  apt:
    update_cache: yes

- name: Install multiple apt packages
  apt:
    force_apt_get: yes
    name: "{{ item }}"
    state: latest
  loop: "{{ apt_packages }}"

- name: Remove useless packages from cache
  apt:
    autoclean: true

- name: Remove package dependencies that are no longer required
  apt:
    autoremove: true

- name: Update local Database
  command: /bin/bash -c "updatedb 2>&1 >> {{ log_file }}"