---  
- name: apt-update packages
  ansible.builtin.apt:
    update_cache: yes

- name: Remove useless packages from cache
  ansible.builtin.apt:
    autoclean: true      
 
- name: Remove package dependencies that are no longer required 
  ansible.builtin.apt:
    autoremove: true        

- name: Install multiple apt packages
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes 
    name: "{{ item }}"
    state: present
  loop: "{{ kali_packages }}"
  
- name: Remove useless packages from cache
  ansible.builtin.apt:
    autoclean: true      
 
- name: Remove package dependencies that are no longer required 
  ansible.builtin.apt:
    autoremove: true        



