- name: "Check if BurpSuiteCA.der exists"
  stat:
    path: /usr/local/share/ca-certificates/BurpSuiteCA.der
  register: burp_cert

- name: "Download CA Certificate to temporary file"
  expect:
    command: "/bin/bash -c timeout 95 java -Djava.awt.headless=true -jar /usr/share/burpsuite/burpsuite.jar &; sleep 30; curl http://localhost:8080/cert -o /home/kali/cacert.der"
    response:
      "accept" : "y"
    timeout: null
  when: burp_cert.stat.exists == False

- name: "Copying CA Certificate to /usr/local/share/ca-certificates"
  copy:
    src: "{{ ansible_env.HOME }}/cacert.der"
    dest: /usr/local/share/ca-certificates/BurpSuiteCA.der
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  when: burp_cert.stat.exists == False

- name: "Remove temporary certificate file"
  file:
    path: "{{ ansible_env.HOME }}/cacert.der"
    state: absent

# Burp extras configuration - not used right now

# - name: Create directory for Burp Suite extras
#   ansible.builtin.file:
#     path: "{{ burpsuite_extras_dir }}"
#     state: directory
#     mode: '0755'
#   become: true
#   become_method: sudo

# - name: Download jar files
#   ansible.builtin.get_url:
#     url: "{{ item.value.url }}"
#     dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
#     checksum: "{{ item.value.checksum }}"
#     mode: '0644'
#   become: true
#   become_method: sudo
#   loop: "{{ lookup('dict', burpsuite_extras_jars) }}"

# - name: Copy BurpSuite Community Config
#   template:
#     src: "templates/UserConfigCommunity.json.j2"
#     dest: "/home/{{ ansible_user_id }}/.BurpSuite/UserConfigCommunity.json"