- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Install python packages
  pip:
    name: '{{ item }}'
    state: latest
    executable: pip3
  loop: '{{ pip_packages }}'

- name: Install pipx
  shell: python3 -m pip install --user pipx