- name: Update install path in install.sh
  command: sed -i -e "s/~/\/opt\/debug/g" /opt/debug/gdb-peda-pwndbg-gef/install.sh

- name: Install debuggers
  expect:
    command: /bin/bash -c "/opt/debug/gdb-peda-pwndbg-gef/install.sh 2>&1 >> {{ log_file }}"
    responses: # skip responses
      "skip" : "y"
    timeout: null

- name: Check if pwndbg is installed
  stat:
    path: "/usr/bin/gdb-pwndbg"
  register: pwndbg_present

- name: Install pwndbg separately
  command:
    cmd: /bin/bash -c "yes | /opt/debug/pwndbg/setup.sh 2>&1 >> {{ log_file }}"
    chdir: /opt/debug/pwndbg/
  when: pwndbg_present.stat.exists == False

- name: Copy debugger binaries
  copy:
    src: "/opt/debug/gdb-peda-pwndbg-gef/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: 0755
  loop:
    - gdb-peda
    - gdb-peda-arm
    - gdb-peda-intel
    - gdb-pwndbg
    - gdb-gef
  when: pwndbg_present.stat.exists == False

- name: Copy gdbinit
  copy:
    src: /opt/debug/gdb-peda-pwndbg-gef/gdbinit
    dest: "{{ ansible_env.HOME }}/.gdbinit"

- name: Update gdbinit
  command: sed -i "s/~\/\(.*\)\/\(.*\)\.py$/\/opt\/debug\/\1\/\2\.py/" "{{ ansible_env.HOME }}"/.gdbinit

- name: Install one-gadget
  command: /bin/bash -c "gem install one_gadget 2>&1 >> {{ log_file }}"

- name: Download patchelf
  git:
    repo: "https://github.com/NixOS/patchelf.git"
    dest: "/opt/binary/patchelf/"
    force: True

- name: Copy install file of patchelf
  copy:
    src: files/install_patchelf.sh
    dest: /opt/binary/patchelf/
    mode: 0755

- name: Install patchelf
  command: /bin/bash -c "/opt/binary/patchelf/install_patchelf.sh 2>&1 >> {{ log_file }}"

- name: Copy pwn templates
  copy:
    src: files/pwn_template/
    dest: /opt/binary/pwn_template