---
# zsh_setup
zsh_user: kali

# file used for command output logging
log_file: /home/kali/.ansible_debug

# Group ownership for the tools that are installed directly to /opt
group: kali
user: kali

# Shared folder (virtualbox)
shared_location: "/media/sf_kali_shared/"

# common apt packages to install
apt_packages:
- autotools-dev
- autoconf
- build-essential
- dnsutils
- ffuf
- gdb
- gem
- ghidra
- gdbserver
- gobuster
- golang
- jq
- libssl-dev
- msfpc
- ncat
- npm
- python3-openssl
- python3-pip
- python3-venv
- seclists

# pip packages
pip_packages:
  - Cython
  - pwntools
  - requests
  - flask-unsign
  - capstone
  - filebytes
  - keystone-engine
  - ropper

# Common Role git repos
git_repos:
  - {path: "/opt/debug", dir_name: "gdb-peda-pwndbg-gef", repo: "https://github.com/apogiatzis/gdb-peda-pwndbg-gef.git"}

git_CTF_repo: "https://github.com/AdamZvara/CTF.git"

 # pip install
pip_install_common:
  # - {path: "/opt/osint-tools/DumpsterDiver"}
  # - {path: "/opt/web-tools/jwt_tool"}

# python setup
python_setup_common:
  # - {path: "/opt/web-tools/dirsearch"}

# Firefox plugins
FirefoxPlugins:
  - "darkreader"
  - "foxyproxy-standard"
  - "wappalyzer"
